//
// STARTER CODE: main.cpp
//
// Adam T Koehler, PhD
// University of Illinois, Chicago
// CS 251, Fall 2022
//
// Project Original Variation By:
// Shanon Reckinger
// University of Illinois, Chicago
//
// This file is the driver for the huffman encoding application.
// Do not edit this file!
//

#include "mainprog.h"
#include "util.h"
#include "hashmap.cpp"
#include "hashmap.h"


int main()
{
    //creativeCompress();
    //creativeDecompress();
    decompress("C:\\Users\\kids\\CLionProjects\\Project 6\\secretmessageTEST.txt");
   //return go();
}